### ISSUE TITLE
Tablo tanımlarında hata

### ISSUE THREAD

**Issue by voransoy** [bulutfon/bulutfon-whmcs#24]
Whmcs sisteminin en son sürümünü kullanmaktayız eklentiyi çalıştırmak istediğimizde aşağıda bulunan hatayı almaktayız.

```
PDOException: SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause in /home/webimcom/public_html/vendor/illuminate/database/Connection.php:441
Stack trace:
#0 /home/webimcom/public_html/vendor/illuminate/database/Connection.php(441): PDOStatement->execute(Array)
#1 /home/webimcom/public_html/vendor/illuminate/database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'create table `m...', Array)
#2 /home/webimcom/public_html/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('create table `m...', Array, Object(Closure))
#3 /home/webimcom/public_html/vendor/illuminate/database/Connection.php(442): Illuminate\Database\Connection->run('create table `m...', Array, Object(Closure))
#4 /home/webimcom/public_html/vendor/illuminate/database/Schema/Blueprint.php(83): Illuminate\Database\Connection->statement('create table `m...')
#5 /home/webimcom/public_html/vendor/illuminate/database/Schema/Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#6 /home/webimcom/public_html/vendor/illuminate/database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#7 /home/webimcom/public_html/modules/addons/bulutfon/bulutfon.php(65): Illuminate\Database\Schema\Builder->create('mod_bulutfon_me...', Object(Closure))
#8 /home/webimcom/public_html/admin/configaddonmods.php(0): bulutfon_activate()
#9 {main}
Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause (SQL: create table `mod_bulutfon_messagelog` (`id` int unsigned not null auto_increment primary key, `userid` int not null, `gsm` varchar(255) not null, `message` longtext not null, `type` varchar(255) not null, `created_at` timestamp default CURRENT_TIMESTAMP not null, `updated_at` timestamp not null default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) default character set utf8 collate utf8_unicode_ci) in /home/webimcom/public_html/vendor/illuminate/database/Connection.php:713
Stack trace:
#0 /home/webimcom/public_html/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('create table `m...', Array, Object(Closure))
#1 /home/webimcom/public_html/vendor/illuminate/database/Connection.php(442): Illuminate\Database\Connection->run('create table `m...', Array, Object(Closure))
#2 /home/webimcom/public_html/vendor/illuminate/database/Schema/Blueprint.php(83): Illuminate\Database\Connection->statement('create table `m...')
#3 /home/webimcom/public_html/vendor/illuminate/database/Schema/Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 /home/webimcom/public_html/vendor/illuminate/database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 /home/webimcom/public_html/modules/addons/bulutfon/bulutfon.php(65): Illuminate\Database\Schema\Builder->create('mod_bulutfon_me...', Object(Closure))
#6 /home/webimcom/public_html/admin/configaddonmods.php(0): bulutfon_activate()
#7 {main}
```

**Comment by hakanersu** [comment]
Bu kullandiginiz veritabani/ayarlari ile ilgili ancak ilerleyen zamanlarda bu alanlari duzenleyebiliriz.
